config/routes.rb
Rails.application.routes.draw do
  
  resources :builders do
    resources :locations
  end

  resources :locations
  resources :projects
  
  get '*unmatched_route', to: 'application#not_found'
  
  

   root 'builders#index'

end

app/models/builder.rb
class Builder < ActiveRecord::Base
    has_many :locations
    
    validates :name, email_format: { message: "doesn't look like an email address" }
    
    
end

app/models/location.rb
class Location < ActiveRecord::Base
    has_many :projects
    belongs_to :builder
    
    validates_presence_of :location_name
    
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :location
    validates_presence_of :name, :bhk
    
    has_attached_file :image_1
    has_attached_file :image_2
    has_attached_file :image_3
    validates_attachment_content_type :image_1, :image_2, :image_3 , content_type: /\Aimage\/.*\Z/
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def not_found
    raise ActionController::RoutingError.new('404 Error, This page can not be found')
  end
  
end

app/controllers/builders_controller.rb
class BuildersController < ApplicationController
  before_action :set_builder, only: [:show, :edit, :update, :destroy]

  # GET /builders
  # GET /builders.json
  def index
    @builders = Builder.all
    @projects = Project.all
    @locations = Location.all
  end

  # GET /builders/1
  # GET /builders/1.json
  def show
    @locations = Builder.find(params[:id]).locations
  end

  # GET /builders/new
  def new
    @builder = Builder.new
  end

  # GET /builders/1/edit
  def edit
  end

  # POST /builders
  # POST /builders.json
  def create
    @builder = Builder.new(builder_params)

    respond_to do |format|
      if @builder.save
        format.html { redirect_to @builder, notice: 'Builder was successfully created.' }
        format.json { render :show, status: :created, location: @builder }
      else
        format.html { render :new }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builders/1
  # PATCH/PUT /builders/1.json
  def update
    respond_to do |format|
      if @builder.update(builder_params)
        format.html { redirect_to @builder, notice: 'Builder was successfully updated.' }
        format.json { render :show, status: :ok, location: @builder }
      else
        format.html { render :edit }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builders/1
  # DELETE /builders/1.json
  def destroy
    @builder.destroy
    respond_to do |format|
      format.html { redirect_to builders_url, notice: 'Builder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_builder
      @builder = Builder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def builder_params
      params.require(:builder).permit(:name)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @builder = Builder.find(params[:builder_id])
    @locations = @builder.locations
  end
  
  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
    @builder = Builder.find(params[:builder_id])
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    @location.builder_id = params[:builder_id]
      if @location.save
        redirect_to builder_location_path(@location.builder_id,@location), notice: "Location was succesfully created."
      else
        render :new
      end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    redirect_to builder_locations_path(@location.builder_id), notice: 'Location was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:location_name, :builder_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :bhk, :location_id, :image_1, :image_2, :image_3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builders_helper.rb
module BuildersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/builders/_form.html.erb
<%= form_for(@builder) do |f| %>

  <% if @builder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@builder.errors.count, "error") %> prohibited this builder from being saved:</h2>

      <ul>
      <% @builder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/builders/edit.html.erb
<h1>Editing Builder</h1>

<%= render 'form' %>

<%= link_to 'Show', @builder %> |
<%= link_to 'Back', builders_path %>

app/views/builders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Builders</h1>

<table border=1>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @builders.each do |builder| %>
      <tr>
        <td><%= builder.name %></td>
        <td><%= link_to 'Show', builder %></td>
        <td><%= link_to 'Edit', edit_builder_path(builder) %></td>
        <td><%= link_to 'Destroy', builder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Builder', new_builder_path %>

app/views/builders/new.html.erb
<h1>New Builder</h1>

<%= render 'form' %>

<%= link_to 'Back', builders_path %>

app/views/builders/show.html.erb
<%= javascript_tag do %>
  function goBack() {
    window.history.back();
}
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Builders Name:</strong>
  <%= @builder.name %>
</p>

	<table border=1>
  <thead>
    <tr>
      <th>Location name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
        <tr>
        <td><%= location.location_name %></td>
        <td><%= link_to 'Show', builder_location_path(location.builder_id, location) %></td>
        <td><%= link_to 'Edit', edit_builder_location_path(location.builder_id, location) %></td>
        <td><%= link_to 'Destroy', builder_location_path(location.builder_id, location), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</br>

<%= link_to 'New Location', new_builder_location_path(@builder) %> 
</br>

<%= link_to 'Edit', edit_builder_path(@builder) %> |
<a href="#" onclick="goBack()">Back</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', builders_path %> ||
<%= link_to 'New Builder', new_builder_path %> ||
<%= link_to 'Projects list', projects_path %>  ||
<%= link_to 'New Project', new_project_path %> ||

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for [@builder,@location] do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_name %><br>
    <%= f.text_field :location_name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', builder_locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Project name</th>
      <th>Builder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.location_name %></td>
        <td><%= location.builder_id %></td>
        <td><%= link_to 'Show', builder_location_path(location.builder_id, location) %></td>
        <td><%= link_to 'Edit', edit_builder_location_path(location.builder_id, location) %></td>
        <td><%= link_to 'Destroy',  builder_location_path(location.builder_id, location), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Location', new_builder_location_path %>

app/views/locations/new.html.erb
<%= javascript_tag do %>
  function goBack() {
    window.history.back();
}
<% end %>

<h1>New Location</h1>

<%= render 'form' %>

<a href="#" onclick="goBack()">Back</a>

app/views/locations/show.html.erb
<%= javascript_tag do %>
  function goBack() {
    window.history.back();
}
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Location name:</strong>
  <%= @location.location_name %>
</p>

<p>
  <strong>Builder:</strong>
  <%= @location.builder.name %>
</p>

<table border=1>
  <thead>
    <tr>
      <th>Project name</th>
      <th>BHK</th>
    </tr>
  </thead>

  <tbody>
    <% for projects in @location.projects %>
    <tr>
    	<td><%= projects.name %></td>
    	<td><%= projects.bhk %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</br>


<% for projects in @location.projects %> 
    <ul>
    	<li><%= image_tag projects.image_1.url %></li>
    	<li><%= image_tag projects.image_2.url %></li>
    	<li><%= image_tag projects.image_3.url %></li>
    </ul>
<% end %>


<%= link_to 'Edit', edit_builder_location_path(@location.builder_id, @location) %> |
<a href="#" onclick="goBack()">Back</a>

app/views/projects/_form.html.erb
<%= form_for (@project), html: { multipart: true } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bhk %><br>
    <%= f.text_field :bhk %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.collection_select :location_id,Location.all,:id,:location_name,prompt: "Select_location" %><br/>
  </div>
  
  <div class="field">
    <%= f.label :image_1 %><br>
    <%= f.file_field :image_1 %>
  </div>
  
  <div class="field">
    <%= f.label :image_2 %><br>
    <%= f.file_field :image_2 %>
  </div>
  
  <div class="field">
    <%= f.label :image_3 %><br>
    <%= f.file_field :image_3 %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table border=1>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bhk</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.bhk %></td>
        <td><%= project.location.location_name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= javascript_tag do %>
function goBack() {
    window.history.back();
}
<% end %>

<p id="notice"><%= notice %></p>

<ul>
  
<li>  
  <strong>Name:</strong>
  <%= @project.name %>
</li>

<li>
  <strong>Bhk:</strong>
  <%= @project.bhk %>
</li>

<li>
  <strong>Location:</strong>
  <%= @project.location.location_name %>
</li>

<li><%= image_tag @project.image_1.url %></li>
<li><%= image_tag @project.image_2.url %></li>
<li><%= image_tag @project.image_3.url %></li>

</ul>

<%= link_to 'Edit', edit_project_path(@project) %> |
<a href="#" onclick="goBack()">Back</a>